{% set name = "freecad-rt" %}

package:
  name: {{ name }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'unknown') }}

source:
  git_url : ../

build:
  number: 2

requirements:
  run_constrained:
    - moab * mpi_openmpi_tempest*
  build:
    - {{ compiler("cxx") }}
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('libselinux') }}            # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('libxext') }}               # [linux]
    - {{ cdt('xorg-x11-server-xvfb') }}  # [linux]
    - {{ cdt('libxau') }}                # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - cmake
    - ninja
    - git
    - sed  # [unix]
  host:
    - boost-cpp
    - python
    - qt
    - occt 7.6
    - xerces-c
    - zlib
    - vtk 9.1
    - swig
    - eigen
    - pybind11
    - coin3d-rt
    - pivy-rt
    - pyside2
    - smesh >=9.9
    - doxygen
    - hdf5 
    - freetype
    - libspnav  # [linux]
    - pcl 1.12.1
    - six
    - ply
  run:
    - python
    - occt 7.6
    - qt
    - pyside2
    - vtk 9.1
    - xerces-c
    - zlib
    - boost-cpp
    - hdf5
    - coin3d-rt
    - pivy-rt
    - smesh >=9.9
    - freetype
    - numpy
    - six
    - future
    - pyyaml
    - libspnav  # [linux]
    - pcl 1.12.1
    - ply
    - gmsh
    - graphviz
    - opencamlib
    - matplotlib

test:
  commands:
    # - FreeCADCmd -t 0
    - FreeCADCmd --version

about:
  home: https://github.com/realthunder/FreeCAD
  license: LGPL2
  license_family: LGPL
  license_file: LICENSE
  summary: 'FreeCAD Link Branch'
  description: |
    FreeCAD Link Branch with various enhancement

extra:
  recipe-maintainers:
    - realthunder
