name: Publish conda

on:
  push:
    tags:
      - "*"

  workflow_dispatch:

jobs:
  conda_deployment_with_new_tag:
    name: Conda deployment of package for platform ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-latest seems to hang on installing 3Dconnexion framework
        # os: [macos-11, ubuntu-latest, windows-latest]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: dist/conda/build_env.yaml    # Path to the build conda environment
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
          # use-mamba: true
          # miniforge-variant: Mambaforge
      # - name: Install mamba build
      #   shell: bash -el {0}
      #   run: mamba install boa -c conda-forge
      - name: Build and upload the conda packages
        uses: realthunder/action-build-and-upload-conda-packages@main
        with:
          meta_yaml_dir: dist/conda
          # mambabuild: true
          user: realthunder
          label: auto
          token: ${{ secrets.ANACONDA_TOKEN }}
          # debug: true
