name: Publish conda

on:
  push:
    tags:
      - "*"

  workflow_dispatch:

jobs:
  conda_deployment_with_new_tag:
    name: Conda build for ${{ matrix.os }} ${{ matrix.arch }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      # fail-fast: false
      matrix:
        os: [macos-11, ubuntu-latest, windows-latest]
        python-version: ["3.10"]
        arch : ["64"]
        include:
          - os: windows-latest
            python-version: "3.8"
            arch : "64"
          - os: ubuntu-latest
            arch: aarch64
            python-version: "3.10"
          - os: macos-11
            arch: arm64
            python-version: "3.10"

    steps:
      - uses: actions/checkout@v3
      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: dist/conda/build_env.yaml    # Path to the build conda environment
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
          # use-mamba: true
          # miniforge-variant: Mambaforge
      # - name: Install mamba build
      #   shell: bash -el {0}
      #   run: mamba install boa -c conda-forge
      - name: Set build variant
        run: |
          if ${{ startsWith(matrix.os, 'macos') }}; then
            platform=osx
          elif ${{ startsWith(matrix.os, 'windows') }}; then
            platform=win
          else
            platform=linux
          fi
          echo "target_platform:\n  $platform-${{ matrix.arch }}" > conda/variant.yaml
          cat conda/variant.yaml
      - name: Build and upload the conda packages
        uses: realthunder/action-build-and-upload-conda-packages@main
        with:
          meta_yaml_dir: dist/conda
          # mambabuild: true
          python-version: ${{ matrix.python-version }}
          user: realthunder
          label: main
          token: ${{ secrets.ANACONDA_TOKEN }}
          # debug: true
